version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: budget_server
      POSTGRES_PASSWORD: budget_server_password
      POSTGRES_DB: budget_server
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
